#499: Upgrade to HtmlUnit 4.x
Xceptance/XLT pull request #503
Opened 2024-06-18 11:09 UTC by jowerner

**ATTENTION:** Please don't squash-merge this pull request. Use a regular merge instead. We need to keep track that the changes originally came from the htmlunit-integration branch.

2025-03-26 08:30 UTC, h-arlt requested changes

2025-03-26 08:30 UTC, h-arlt commented on pom.xml
We reference some Selenium Libs that HU does not. Is this intended (ie-driver and safari-driver may be explicitly shipped w/ XLT :shrug: ) ?
* org.seleniumhq.selenium:selenium-devtools-v85:jar:4.29.0
* org.seleniumhq.selenium:selenium-devtools-v131:jar:4.29.0
* org.seleniumhq.selenium:selenium-devtools-v132:jar:4.29.0
* org.seleniumhq.selenium:selenium-ie-driver:jar:4.29.0
* org.seleniumhq.selenium:selenium-java:jar:4.29.0
* org.seleniumhq.selenium:selenium-safari-driver:jar:4.29.0

2025-04-02 11:24 UTC, jowerner commented on src/main/java/com/xceptance/xlt/engine/xltdriver/HtmlUnitDriver.java
Done.

2025-04-02 11:24 UTC, jowerner commented on pom.xml
Done.

2025-04-02 11:26 UTC, jowerner commented on pom.xml
> +            <version>6.55.0</version>
Done. For this to work, I had to add a new dependency and tweak the test Ant script.

2025-04-02 11:27 UTC, jowerner commented on pom.xml
>              <artifactId>checkstyle</artifactId>
HU still uses the Checkstyle version property, but not in the dependencies section, but the build section.

2025-04-02 11:27 UTC, jowerner commented on pom.xml
Done.

2025-04-02 11:28 UTC, jowerner commented on pom.xml
Added these as well.

2025-04-02 11:40 UTC, jowerner commented on pom.xml
We have always shipped the full Selenium bundle as part of XLT. Do we want to change that now?

2025-04-02 14:54 UTC, h-arlt commented on pom.xml
Just because we did so in the past doesn't mean that we should continue to do so. HU doesn't ship entire Selenium bundle because certain browser are not used anymore (retired or replaced).

IMO XLT should support only the common use-cases and running IE is probably not that common (anymore) since M$ retired IE a while ago. XLT should ship support for modern browsers only. In case users have the need for running with ancient browsers, they can pull in support for that by their own. That's not the responsibility of XLT.

https://techcommunity.microsoft.com/blog/windows-itpro-blog/new-testing-tools-to-help-prepare-for-ie-retirement/3059947

2025-04-02 15:22 UTC, h-arlt commented on pom.xml
Dropping support for retired/ancient browsers is a separate issue. 

But we might think about to exclude the outdated devtool JARs at least.

2025-04-03 05:28 UTC, h-arlt approved these changes

2025-04-03 10:56 UTC, merged