#527: Add response codes chart
Xceptance/XLT pull request #528
Opened 2024-10-23 11:27 UTC by jowerner

2024-11-13 10:10 UTC, rschwietzke requested changes
Sweat. Is there a way to get the numbers aligned in the front? I know that is known, but it looks odd that the response code at the vertical axis is changing is position depending on the count. How about just putting that to the right of the the chart instead?

![image](https://github.com/user-attachments/assets/158d9499-fd97-4fb1-801a-ad0a5633a26d)

2024-11-14 14:28 UTC, jowerner commented
> Sweat. Is there a way to get the numbers aligned in the front? I know that is known, but it looks odd that the response code at the vertical axis is changing is position depending on the count. How about just putting that to the right of the the chart instead?

Didn't find a way to left-align the axis labels, so we put the response code to the right side of the plots as suggested.

2024-11-18 13:06 UTC, rschwietzke approved these changes

2024-11-18 13:08 UTC, rschwietzke commented
The new chart concept with the "right axis"  text looks good.

2024-11-18 13:25 UTC, merged